package org.ebix.umm.uml2text.ods;

import org.ebix.umm.uml2text.ods.OdsPart;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Styles extends OdsPart {
  public String fileName() {
    return "styles.xml";
  }
  
  public String content() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<office:document-styles ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:table=\"urn:oasis:names:tc:opendocument:xmlns:table:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:xlink=\"http://www.w3.org/1999/xlink\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:dc=\"http://purl.org/dc/elements/1.1/\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:number=\"urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentation:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:chart=\"urn:oasis:names:tc:opendocument:xmlns:chart:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:dr3d=\"urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:math=\"http://www.w3.org/1998/Math/MathML\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:form=\"urn:oasis:names:tc:opendocument:xmlns:form:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:script=\"urn:oasis:names:tc:opendocument:xmlns:script:1.0\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:ooo=\"http://openoffice.org/2004/office\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:ooow=\"http://openoffice.org/2004/writer\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:oooc=\"http://openoffice.org/2004/calc\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:dom=\"http://www.w3.org/2001/xml-events\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:rpt=\"http://openoffice.org/2005/report\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:of=\"urn:oasis:names:tc:opendocument:xmlns:of:1.2\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:grddl=\"http://www.w3.org/2003/g/data-view#\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("xmlns:css3t=\"http://www.w3.org/TR/css3-text/\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("office:version=\"1.1\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<office:font-face-decls>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:font-face style:name=\"Liberation Sans\" svg:font-family=\"&apos;Liberation Sans&apos;\" style:font-family-generic=\"swiss\" style:font-pitch=\"variable\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:font-face style:name=\"DejaVu Sans\" svg:font-family=\"&apos;DejaVu Sans&apos;\" style:font-family-generic=\"system\" style:font-pitch=\"variable\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:font-face style:name=\"Lohit Hindi\" svg:font-family=\"&apos;Lohit Hindi&apos;\" style:font-family-generic=\"system\" style:font-pitch=\"variable\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:font-face style:name=\"WenQuanYi Micro Hei\" svg:font-family=\"&apos;WenQuanYi Micro Hei&apos;\" style:font-family-generic=\"system\" style:font-pitch=\"variable\"/>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</office:font-face-decls>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<office:styles>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:default-style style:family=\"table-cell\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:paragraph-properties style:tab-stop-distance=\"0.5in\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:text-properties style:font-name=\"Liberation Sans\" fo:language=\"en\" fo:country=\"US\" style:font-name-asian=\"DejaVu Sans\" style:language-asian=\"zh\" style:country-asian=\"CN\" style:font-name-complex=\"DejaVu Sans\" style:language-complex=\"hi\" style:country-complex=\"IN\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:default-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<number:number-style style:name=\"N0\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:number number:min-integer-digits=\"1\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</number:number-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<number:currency-style style:name=\"N104P0\" style:volatile=\"true\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:currency-symbol number:language=\"en\" number:country=\"US\">$</number:currency-symbol>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:number number:decimal-places=\"2\" number:min-integer-digits=\"1\" number:grouping=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</number:currency-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<number:currency-style style:name=\"N104\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:text-properties fo:color=\"#ff0000\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:text>-</number:text>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:currency-symbol number:language=\"en\" number:country=\"US\">$</number:currency-symbol>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<number:number number:decimal-places=\"2\" number:min-integer-digits=\"1\" number:grouping=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:map style:condition=\"value()&gt;=0\" style:apply-style-name=\"N104P0\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</number:currency-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:style style:name=\"Default\" style:family=\"table-cell\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:text-properties style:font-name-asian=\"WenQuanYi Micro Hei\" style:font-name-complex=\"Lohit Hindi\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:style style:name=\"Result\" style:family=\"table-cell\" style:parent-style-name=\"Default\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:text-properties fo:font-style=\"italic\" style:text-underline-style=\"solid\" style:text-underline-width=\"auto\" style:text-underline-color=\"font-color\" fo:font-weight=\"bold\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:style style:name=\"Result2\" style:family=\"table-cell\" style:parent-style-name=\"Result\" style:data-style-name=\"N104\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:style style:name=\"Heading\" style:family=\"table-cell\" style:parent-style-name=\"Default\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:table-cell-properties style:text-align-source=\"fix\" style:repeat-content=\"false\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:paragraph-properties fo:text-align=\"center\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:text-properties fo:font-size=\"16pt\" fo:font-style=\"italic\" fo:font-weight=\"bold\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:style style:name=\"Heading1\" style:family=\"table-cell\" style:parent-style-name=\"Heading\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:table-cell-properties style:rotation-angle=\"90\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:style>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</office:styles>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<office:automatic-styles>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:page-layout style:name=\"Mpm1\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:page-layout-properties style:writing-mode=\"lr-tb\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header-style>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:header-footer-properties fo:min-height=\"0.2957in\" fo:margin-left=\"0in\" fo:margin-right=\"0in\" fo:margin-bottom=\"0.0984in\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</style:header-style>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer-style>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:header-footer-properties fo:min-height=\"0.2957in\" fo:margin-left=\"0in\" fo:margin-right=\"0in\" fo:margin-top=\"0.0984in\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</style:footer-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:page-layout>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:page-layout style:name=\"Mpm2\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:page-layout-properties style:writing-mode=\"lr-tb\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header-style>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:header-footer-properties fo:min-height=\"0.2957in\" fo:margin-left=\"0in\" fo:margin-right=\"0in\" fo:margin-bottom=\"0.0984in\" fo:border=\"2.49pt solid #000000\" fo:padding=\"0.0071in\" fo:background-color=\"#c0c0c0\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<style:background-image/>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</style:header-footer-properties>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</style:header-style>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer-style>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:header-footer-properties fo:min-height=\"0.2957in\" fo:margin-left=\"0in\" fo:margin-right=\"0in\" fo:margin-top=\"0.0984in\" fo:border=\"2.49pt solid #000000\" fo:padding=\"0.0071in\" fo:background-color=\"#c0c0c0\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<style:background-image/>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</style:header-footer-properties>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</style:footer-style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:page-layout>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</office:automatic-styles>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<office:master-styles>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:master-page style:name=\"Default\" style:page-layout-name=\"Mpm1\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header><text:p><text:sheet-name>???</text:sheet-name></text:p></style:header>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header-left style:display=\"false\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer><text:p>Page <text:page-number>1</text:page-number></text:p></style:footer>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer-left style:display=\"false\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:master-page>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style:master-page style:name=\"Report\" style:page-layout-name=\"Mpm2\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:region-left><text:p><text:sheet-name>???</text:sheet-name> (<text:title>???</text:title>)</text:p></style:region-left>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<style:region-right><text:p><text:date style:data-style-name=\"N2\" text:date-value=\"2012-07-29\">07/29/2012</text:date>, <text:time>19:00:13</text:time></text:p></style:region-right>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</style:header>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:header-left style:display=\"false\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer><text:p>Page <text:page-number>1</text:page-number> / <text:page-count>99</text:page-count></text:p></style:footer>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<style:footer-left style:display=\"false\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</style:master-page>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</office:master-styles>");
    _builder.newLine();
    _builder.append("</office:document-styles>");
    _builder.newLine();
    return _builder.toString();
  }
}
