/*
 * generated by Xtext
 */
package org.ebix.umm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmmUiModule extends org.ebix.umm.ui.AbstractUmmUiModule {
	public UmmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
