/*
 * generated by Xtext
 */
package org.ebix.umm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ebix.umm.ui.internal.UmmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UmmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UmmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UmmActivator.getInstance().getInjector(UmmActivator.ORG_EBIX_UMM_UMM);
	}
	
}
