/**
 * generated by Xtext
 */
package org.ebix.umm.scoping;

import com.google.common.base.Objects;
import org.ebix.umm.umm.ABIE;
import org.ebix.umm.umm.ABIEProperty;
import org.ebix.umm.umm.ASBIE;
import org.ebix.umm.umm.BBIE;
import org.ebix.umm.umm.BDT;
import org.ebix.umm.umm.BDTProperty;
import org.ebix.umm.umm.Constraint;
import org.ebix.umm.umm.ContextRef;
import org.ebix.umm.umm.MA;
import org.ebix.umm.umm.MAProperty;
import org.ebix.umm.umm.OclArrow;
import org.ebix.umm.umm.OclForAll;
import org.ebix.umm.umm.OclInvariant;
import org.ebix.umm.umm.OclPathFeatureHead;
import org.ebix.umm.umm.OclPathSelfHead;
import org.ebix.umm.umm.OclPathTail;
import org.ebix.umm.umm.OclRef;
import org.ebix.umm.umm.OclReference;
import org.ebix.umm.umm.OclValue;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class UmmScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope getScope(final EObject context, final EReference reference) {
    return super.getScope(context, reference);
  }
  
  public IScope scope_OclPathFeatureHead_feature(final OclInvariant oclInvariant, final EReference eRef) {
    EObject _eContainer = oclInvariant.eContainer();
    final ContextRef context = ((Constraint) _eContainer).getContext();
    return this.getScope(context);
  }
  
  public IScope scope_OclPathFeatureHead_feature(final OclForAll forAll, final EReference eRef) {
    IScope scope = IScope.NULLSCOPE;
    EObject _eContainer = forAll.eContainer();
    final OclValue value = ((OclArrow) _eContainer).getLeft();
    if ((value instanceof OclReference)) {
      ContextRef _type = this.getType(((OclReference) value));
      IScope _scope = this.getScope(_type);
      scope = _scope;
    }
    return scope;
  }
  
  public IScope scope_OclPathTail_feature(final OclPathTail pathTail, final EReference eRef) {
    ContextRef _previousType = this.previousType(pathTail);
    return this.getScope(_previousType);
  }
  
  /**
   * Returns the {@link ContextRef} instance pointed to by either the previous
   * path element ({@link OclPathSelfHead}, {@link OclPathFeatureHead} or
   * {@link OclPathTail}) or by the containing element (either an
   * {@link OclInvariant} or {@link OclForAll}).
   * 
   * @throws RuntimeException
   *             if the previous type cannot be determined.
   */
  public ContextRef previousType(final OclPathTail pathTail) {
    ContextRef context = null;
    final EObject container = pathTail.eContainer();
    if ((container instanceof OclPathFeatureHead)) {
      OclRef _feature = ((OclPathFeatureHead) container).getFeature();
      ContextRef _referedType = this.getReferedType(_feature);
      context = _referedType;
    } else {
      if ((container instanceof OclPathSelfHead)) {
        EObject container2 = container.eContainer();
        boolean _not = (!(container2 instanceof Constraint));
        boolean _while = _not;
        while (_while) {
          EObject _eContainer = container2.eContainer();
          container2 = _eContainer;
          boolean _not_1 = (!(container2 instanceof Constraint));
          _while = _not_1;
        }
        final Constraint constraint = ((Constraint) container2);
        ContextRef _context = constraint.getContext();
        context = _context;
      } else {
        if ((container instanceof OclPathTail)) {
          final OclRef oclRef = ((OclPathTail) container).getFeature();
          ContextRef _referedType_1 = this.getReferedType(oclRef);
          context = _referedType_1;
        }
      }
    }
    return context;
  }
  
  public ContextRef getType(final OclReference oclReference) {
    ContextRef type = null;
    if ((oclReference instanceof OclPathFeatureHead)) {
      final OclPathFeatureHead head = ((OclPathFeatureHead) oclReference);
      OclPathTail _tail = head.getTail();
      boolean _notEquals = (!Objects.equal(_tail, null));
      if (_notEquals) {
        OclPathTail _tail_1 = head.getTail();
        ContextRef _resultType = this.resultType(_tail_1);
        type = _resultType;
      } else {
        OclRef _feature = head.getFeature();
        ContextRef _referedType = this.getReferedType(_feature);
        type = _referedType;
      }
    } else {
      if ((oclReference instanceof OclPathSelfHead)) {
        OclPathTail _path = ((OclPathSelfHead) oclReference).getPath();
        ContextRef _resultType_1 = this.resultType(_path);
        type = _resultType_1;
      }
    }
    return type;
  }
  
  /**
   * Looks up the end of the path and returns its type (of meta type
   * {@link Entity}).
   */
  public ContextRef resultType(final OclPathTail pathTail) {
    OclPathTail pathEnd = pathTail;
    OclPathTail _tail = pathEnd.getTail();
    boolean _notEquals = (!Objects.equal(_tail, null));
    boolean _while = _notEquals;
    while (_while) {
      OclPathTail _tail_1 = pathEnd.getTail();
      pathEnd = _tail_1;
      OclPathTail _tail_2 = pathEnd.getTail();
      boolean _notEquals_1 = (!Objects.equal(_tail_2, null));
      _while = _notEquals_1;
    }
    OclRef _feature = pathEnd.getFeature();
    return this.getReferedType(_feature);
  }
  
  public IScope getScope(final ContextRef type) {
    IScope result = IScope.NULLSCOPE;
    boolean _matched = false;
    if (!_matched) {
      if (type instanceof MA) {
        final MA _mA = (MA)type;
        if (true) {
          _matched=true;
          EList<MAProperty> _properties = _mA.getProperties();
          IScope _scopeFor = Scopes.scopeFor(_properties);
          result = _scopeFor;
        }
      }
    }
    if (!_matched) {
      if (type instanceof ABIE) {
        final ABIE _aBIE = (ABIE)type;
        if (true) {
          _matched=true;
          EList<ABIEProperty> _properties = _aBIE.getProperties();
          IScope _scopeFor = Scopes.scopeFor(_properties);
          result = _scopeFor;
        }
      }
    }
    if (!_matched) {
      if (type instanceof BDT) {
        final BDT _bDT = (BDT)type;
        if (true) {
          _matched=true;
          EList<BDTProperty> _properties = _bDT.getProperties();
          IScope _scopeFor = Scopes.scopeFor(_properties);
          result = _scopeFor;
        }
      }
    }
    return result;
  }
  
  private ContextRef getReferedType(final OclRef oclRef) {
    ContextRef type = null;
    boolean _matched = false;
    if (!_matched) {
      if (oclRef instanceof MAProperty) {
        final MAProperty _mAProperty = (MAProperty)oclRef;
        if (true) {
          _matched=true;
          ABIE _type = _mAProperty.getType();
          type = _type;
        }
      }
    }
    if (!_matched) {
      if (oclRef instanceof ASBIE) {
        final ASBIE _aSBIE = (ASBIE)oclRef;
        if (true) {
          _matched=true;
          ABIE _type = _aSBIE.getType();
          type = _type;
        }
      }
    }
    if (!_matched) {
      if (oclRef instanceof BBIE) {
        final BBIE _bBIE = (BBIE)oclRef;
        if (true) {
          _matched=true;
          BDT _type = _bBIE.getType();
          type = _type;
        }
      }
    }
    return type;
  }
}
