/*
 * generated by Xtext
 */
package org.ebix.umm;

import org.ebix.umm.generator.UmmOutputConfigurationProvider;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

import com.google.inject.Binder;
import com.google.inject.Singleton;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UmmRuntimeModule extends org.ebix.umm.AbstractUmmRuntimeModule {

	@Override
	public void configure(Binder binder) {
	    super.configure(binder);

	    binder.bind(IOutputConfigurationProvider.class).to(UmmOutputConfigurationProvider.class).in(Singleton.class);
	}
}
