/*
* generated by Xtext
*/
package org.ebix.umm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UmmStandaloneSetup extends UmmStandaloneSetupGenerated{

	public static void doSetup() {
		new UmmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

