/*
* generated by Xtext
*/
package org.ebix.umm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ebix.umm.services.UmmGrammarAccess;

public class UmmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UmmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_OCL_COMMENT", "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ebix.umm.parser.antlr.internal.InternalUmmParser createParser(XtextTokenStream stream) {
		return new org.ebix.umm.parser.antlr.internal.InternalUmmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Library";
	}
	
	public UmmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
