/*
 * generated by Xtext
 */
package org.ebix.umm.ui.contentassist

import org.ebix.umm.ui.contentassist.AbstractUmmProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class UmmProposalProvider extends AbstractUmmProposalProvider {
}
