package org.ebix.umm.templates.xsd;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class DateTypesSchema {
  private final String fileName = "ebIX_DateTypeExtension.xsd";
  
  public String fileName(final String directory) {
    return ((directory + "/") + this.fileName);
  }
  
  public String getFileName() {
    return this.fileName;
  }
  
  public CharSequence compile() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<!-- ==================================================================== -->");
    _builder.newLine();
    _builder.append("<!-- ===== XML Schema Builtin Type Extension XML Schema File \t\t\t\t\t\t\t\t    ===== -->");
    _builder.newLine();
    _builder.append("<!-- ==================================================================== -->");
    _builder.newLine();
    _builder.append("<!--");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("Schema agency: \t\tUN/CEFACT ");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("Schema version:\t\t1.0 DRAFT");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("Schema date: \t    12 April 2010");
    _builder.newLine();
    _builder.append("  \t");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("Copyright (C) UN/CEFACT (2010). All Rights Reserved.");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("This document and translations of it may be copied and furnished to others, ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("and derivative works that comment on or otherwise explain it or assist ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("in its implementation may be prepared, copied, published and distributed, ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("in whole or in part, without restriction of any kind, provided that the ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("above copyright notice and this paragraph are included on all such copies ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("and derivative works. However, this document itself may not be modified in ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("any way, such as by removing the copyright notice or references to ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("UN/CEFACT, except as needed for the purpose of developing UN/CEFACT ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("specifications, in which case the procedures for copyrights defined in the ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("UN/CEFACT Intellectual Property Rights document must be followed, or as ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("required to translate it into languages other than English.");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("The limited permissions granted above are perpetual and will not be revoked ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("by UN/CEFACT or its successors or assigns.");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("This document and the information contained herein is provided on an \"AS IS\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("basis and UN/CEFACT DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("BUT NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION HEREIN WILL ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("NOT INFRINGE ANY RIGHTS OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("FITNESS FOR A PARTICULAR PURPOSE.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("-->");
    _builder.newLine();
    _builder.append("<xsd:schema xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xbt=\"urn:un:unece:uncefact:data:common:1:draft\" targetNamespace=\"urn:un:unece:uncefact:data:common:1:draft\" elementFormDefault=\"qualified\" attributeFormDefault=\"unqualified\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- =================================================================== -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- ===== Type Definitions ===== -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!-- =================================================================== -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--====== Duration types ========-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDurationType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: nW</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"\\d+W\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--====== Date types ========-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DD</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:date\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DD</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:gDay\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-3][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDD</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3] [0-9]{2}\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-D</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: --MM--</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:gMonth\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]--\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: --MM-DD</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:gMonthDay\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-D</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDD</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearMonthType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:gYearMonth\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-D</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--====== Time types ========-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"HourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: hh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"HourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MinuteType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MinuteSecondType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"SecondType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: --ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"TimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: hh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:time\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"TimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: hh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:time\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"TimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: hh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:time\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--====== DateTime types =====-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<!--========================-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DDThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DDThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DDThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:dateTime\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DDThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:dateTime\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DateTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-MM-DDThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:dateTime\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DDThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-3][0-9]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DDThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-3][0-9]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DDThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DDThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: ---DDThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"---[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-DThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-DThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-DThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-DThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfWeekTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -W-DThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDDThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3][0-9]{2}T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDDThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDDThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDDThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"DayOfYearTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -DDDThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -MM-DDThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayHourMinuteType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -MM-DDThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -MM-DDThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -MM-DDThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"MonthDayTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -MM-DDThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"--[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-DThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayHourMinuteType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-DThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-DThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-DThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"WeekDayTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: -Www-DThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDDThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDDThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDDThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDDThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearDayTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-DDDThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-[0-3][0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayHourLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-DThh</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]T[0-2][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayHourMinuteLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-DThh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayTimeLocalType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-DThh:mm:ss</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayTimeUTCOffsetType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-DThh:mm:ss+hh:mm</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*[\\+|-][0-2][0-9]:[0-6][0-9]\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<xsd:simpleType name=\"YearWeekDayTimeUTCType\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:documentation>ISO 8601 format: YYYY-Www-DThh:mm:ssZ</xsd:documentation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:annotation>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<xsd:restriction base=\"xsd:token\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<xsd:pattern value=\"[0-9]{4}-W[0-5][0-9]-[1-7]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]*Z\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</xsd:restriction>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</xsd:simpleType>");
    _builder.newLine();
    _builder.append("</xsd:schema>");
    _builder.newLine();
    return _builder;
  }
}
